# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showoff', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweets',
            new_name='Tweet',
        ),
        migrations.AddField(
            model_name='target',
            name='target_handle',
            field=models.CharField(default='some_handle', max_length=15),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_name',
            field=models.CharField(max_length=30),
        ),
    ]
